# Generated by Django 2.2.5 on 2019-09-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=128)),
                ('img_sign', models.IntegerField(default=-1, null=True)),
                ('img_result', models.IntegerField(default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=16)),
                ('user_password', models.CharField(max_length=16)),
                ('user_power', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
